spring:
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5432/payments
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    #generate-ddl: true
    #show-sql: true
  data:
    mongodb:
      username: admin
      password: admin
      database: training
      host: localhost
      port: 27017
      authentication-database: admin
      auto-index-creation: true
  messages:
    basename: exceptions,text
jwt:
  secret: sdfbk3js1zcvabfvae